/*
Permit.io API

 Authorization as a service

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// Pdp struct for Pdp
type Pdp struct {
	BACKEND_SERVICE_URL                       string `json:"BACKEND_SERVICE_URL"`
	OPA_DECISION_LOG_INGRESS_ROUTE            string `json:"OPA_DECISION_LOG_INGRESS_ROUTE"`
	OPA_DECISION_LOG_INGRESS_BACKEND_TIER_URL string `json:"OPA_DECISION_LOG_INGRESS_BACKEND_TIER_URL"`
}

// NewPdp instantiates a new Pdp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPdp(bACKENDSERVICEURL string, oPADECISIONLOGINGRESSROUTE string, oPADECISIONLOGINGRESSBACKENDTIERURL string) *Pdp {
	this := Pdp{}
	this.BACKEND_SERVICE_URL = bACKENDSERVICEURL
	this.OPA_DECISION_LOG_INGRESS_ROUTE = oPADECISIONLOGINGRESSROUTE
	this.OPA_DECISION_LOG_INGRESS_BACKEND_TIER_URL = oPADECISIONLOGINGRESSBACKENDTIERURL
	return &this
}

// NewPdpWithDefaults instantiates a new Pdp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPdpWithDefaults() *Pdp {
	this := Pdp{}
	return &this
}

// GetBACKEND_SERVICE_URL returns the BACKEND_SERVICE_URL field value
func (o *Pdp) GetBACKEND_SERVICE_URL() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BACKEND_SERVICE_URL
}

// GetBACKEND_SERVICE_URLOk returns a tuple with the BACKEND_SERVICE_URL field value
// and a boolean to check if the value has been set.
func (o *Pdp) GetBACKEND_SERVICE_URLOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BACKEND_SERVICE_URL, true
}

// SetBACKEND_SERVICE_URL sets field value
func (o *Pdp) SetBACKEND_SERVICE_URL(v string) {
	o.BACKEND_SERVICE_URL = v
}

// GetOPA_DECISION_LOG_INGRESS_ROUTE returns the OPA_DECISION_LOG_INGRESS_ROUTE field value
func (o *Pdp) GetOPA_DECISION_LOG_INGRESS_ROUTE() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OPA_DECISION_LOG_INGRESS_ROUTE
}

// GetOPA_DECISION_LOG_INGRESS_ROUTEOk returns a tuple with the OPA_DECISION_LOG_INGRESS_ROUTE field value
// and a boolean to check if the value has been set.
func (o *Pdp) GetOPA_DECISION_LOG_INGRESS_ROUTEOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OPA_DECISION_LOG_INGRESS_ROUTE, true
}

// SetOPA_DECISION_LOG_INGRESS_ROUTE sets field value
func (o *Pdp) SetOPA_DECISION_LOG_INGRESS_ROUTE(v string) {
	o.OPA_DECISION_LOG_INGRESS_ROUTE = v
}

// GetOPA_DECISION_LOG_INGRESS_BACKEND_TIER_URL returns the OPA_DECISION_LOG_INGRESS_BACKEND_TIER_URL field value
func (o *Pdp) GetOPA_DECISION_LOG_INGRESS_BACKEND_TIER_URL() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OPA_DECISION_LOG_INGRESS_BACKEND_TIER_URL
}

// GetOPA_DECISION_LOG_INGRESS_BACKEND_TIER_URLOk returns a tuple with the OPA_DECISION_LOG_INGRESS_BACKEND_TIER_URL field value
// and a boolean to check if the value has been set.
func (o *Pdp) GetOPA_DECISION_LOG_INGRESS_BACKEND_TIER_URLOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OPA_DECISION_LOG_INGRESS_BACKEND_TIER_URL, true
}

// SetOPA_DECISION_LOG_INGRESS_BACKEND_TIER_URL sets field value
func (o *Pdp) SetOPA_DECISION_LOG_INGRESS_BACKEND_TIER_URL(v string) {
	o.OPA_DECISION_LOG_INGRESS_BACKEND_TIER_URL = v
}

func (o Pdp) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["BACKEND_SERVICE_URL"] = o.BACKEND_SERVICE_URL
	}
	if true {
		toSerialize["OPA_DECISION_LOG_INGRESS_ROUTE"] = o.OPA_DECISION_LOG_INGRESS_ROUTE
	}
	if true {
		toSerialize["OPA_DECISION_LOG_INGRESS_BACKEND_TIER_URL"] = o.OPA_DECISION_LOG_INGRESS_BACKEND_TIER_URL
	}
	return json.Marshal(toSerialize)
}

type NullablePdp struct {
	value *Pdp
	isSet bool
}

func (v NullablePdp) Get() *Pdp {
	return v.value
}

func (v *NullablePdp) Set(val *Pdp) {
	v.value = val
	v.isSet = true
}

func (v NullablePdp) IsSet() bool {
	return v.isSet
}

func (v *NullablePdp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePdp(val *Pdp) *NullablePdp {
	return &NullablePdp{value: val, isSet: true}
}

func (v NullablePdp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePdp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
