/*
Permit.io API

 Authorization as a service

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
)

// ParentId Parent Condition Set
type ParentId struct {
	string *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *ParentId) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into string
	err = json.Unmarshal(data, &dst.string)
	if err == nil {
		jsonstring, _ := json.Marshal(dst.string)
		if string(jsonstring) == "{}" { // empty struct
			dst.string = nil
		} else {
			return nil // data stored in dst.string, return on the first match
		}
	} else {
		dst.string = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(ParentId)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *ParentId) MarshalJSON() ([]byte, error) {
	if src.string != nil {
		return json.Marshal(&src.string)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableParentId struct {
	value *ParentId
	isSet bool
}

func (v NullableParentId) Get() *ParentId {
	return v.value
}

func (v *NullableParentId) Set(val *ParentId) {
	v.value = val
	v.isSet = true
}

func (v NullableParentId) IsSet() bool {
	return v.isSet
}

func (v *NullableParentId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableParentId(val *ParentId) *NullableParentId {
	return &NullableParentId{value: val, isSet: true}
}

func (v NullableParentId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableParentId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
