/*
Permit.io API

 Authorization as a service

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// ProjectUpdate struct for ProjectUpdate
type ProjectUpdate struct {
	// The name of the project
	Name *string `json:"name,omitempty"`
	// a longer description outlining the project objectives
	Description *string `json:"description,omitempty"`
	// the settings for this project
	Settings map[string]interface{} `json:"settings,omitempty"`
	// the id of the policy repo to use for this project
	ActivePolicyRepoId *string `json:"active_policy_repo_id,omitempty"`
}

// NewProjectUpdate instantiates a new ProjectUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectUpdate() *ProjectUpdate {
	this := ProjectUpdate{}
	return &this
}

// NewProjectUpdateWithDefaults instantiates a new ProjectUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectUpdateWithDefaults() *ProjectUpdate {
	this := ProjectUpdate{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ProjectUpdate) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectUpdate) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ProjectUpdate) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ProjectUpdate) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ProjectUpdate) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectUpdate) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ProjectUpdate) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ProjectUpdate) SetDescription(v string) {
	o.Description = &v
}

// GetSettings returns the Settings field value if set, zero value otherwise.
func (o *ProjectUpdate) GetSettings() map[string]interface{} {
	if o == nil || IsNil(o.Settings) {
		var ret map[string]interface{}
		return ret
	}
	return o.Settings
}

// GetSettingsOk returns a tuple with the Settings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectUpdate) GetSettingsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Settings) {
		return map[string]interface{}{}, false
	}
	return o.Settings, true
}

// HasSettings returns a boolean if a field has been set.
func (o *ProjectUpdate) HasSettings() bool {
	if o != nil && !IsNil(o.Settings) {
		return true
	}

	return false
}

// SetSettings gets a reference to the given map[string]interface{} and assigns it to the Settings field.
func (o *ProjectUpdate) SetSettings(v map[string]interface{}) {
	o.Settings = v
}

// GetActivePolicyRepoId returns the ActivePolicyRepoId field value if set, zero value otherwise.
func (o *ProjectUpdate) GetActivePolicyRepoId() string {
	if o == nil || IsNil(o.ActivePolicyRepoId) {
		var ret string
		return ret
	}
	return *o.ActivePolicyRepoId
}

// GetActivePolicyRepoIdOk returns a tuple with the ActivePolicyRepoId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectUpdate) GetActivePolicyRepoIdOk() (*string, bool) {
	if o == nil || IsNil(o.ActivePolicyRepoId) {
		return nil, false
	}
	return o.ActivePolicyRepoId, true
}

// HasActivePolicyRepoId returns a boolean if a field has been set.
func (o *ProjectUpdate) HasActivePolicyRepoId() bool {
	if o != nil && !IsNil(o.ActivePolicyRepoId) {
		return true
	}

	return false
}

// SetActivePolicyRepoId gets a reference to the given string and assigns it to the ActivePolicyRepoId field.
func (o *ProjectUpdate) SetActivePolicyRepoId(v string) {
	o.ActivePolicyRepoId = &v
}

func (o ProjectUpdate) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Settings) {
		toSerialize["settings"] = o.Settings
	}
	if !IsNil(o.ActivePolicyRepoId) {
		toSerialize["active_policy_repo_id"] = o.ActivePolicyRepoId
	}
	return json.Marshal(toSerialize)
}

type NullableProjectUpdate struct {
	value *ProjectUpdate
	isSet bool
}

func (v NullableProjectUpdate) Get() *ProjectUpdate {
	return v.value
}

func (v *NullableProjectUpdate) Set(val *ProjectUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectUpdate(val *ProjectUpdate) *NullableProjectUpdate {
	return &NullableProjectUpdate{value: val, isSet: true}
}

func (v NullableProjectUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
