/*
Permit.io API

 Authorization as a service

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
	"time"
)

// OrganizationReadWithAPIKey struct for OrganizationReadWithAPIKey
type OrganizationReadWithAPIKey struct {
	// A URL-friendly name of the organization (i.e: slug). You will be able to query later using this key instead of the id (UUID) of the organization.
	Key string `json:"key"`
	// Unique id of the organization
	Id string `json:"id"`
	// Date and time when the organization was created (ISO_8601 format).
	CreatedAt time.Time `json:"created_at"`
	// Date and time when the organization was last updated/modified (ISO_8601 format).
	UpdatedAt time.Time `json:"updated_at"`
	// The name of the organization, usually it's your company's name.
	Name string `json:"name"`
	// the settings for this project
	Settings     map[string]interface{} `json:"settings,omitempty"`
	ApiKeyId     *string                `json:"api_key_id,omitempty"`
	ApiKeySecret *string                `json:"api_key_secret,omitempty"`
}

// NewOrganizationReadWithAPIKey instantiates a new OrganizationReadWithAPIKey object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationReadWithAPIKey(key string, id string, createdAt time.Time, updatedAt time.Time, name string) *OrganizationReadWithAPIKey {
	this := OrganizationReadWithAPIKey{}
	this.Key = key
	this.Id = id
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.Name = name
	return &this
}

// NewOrganizationReadWithAPIKeyWithDefaults instantiates a new OrganizationReadWithAPIKey object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationReadWithAPIKeyWithDefaults() *OrganizationReadWithAPIKey {
	this := OrganizationReadWithAPIKey{}
	return &this
}

// GetKey returns the Key field value
func (o *OrganizationReadWithAPIKey) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *OrganizationReadWithAPIKey) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *OrganizationReadWithAPIKey) SetKey(v string) {
	o.Key = v
}

// GetId returns the Id field value
func (o *OrganizationReadWithAPIKey) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *OrganizationReadWithAPIKey) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *OrganizationReadWithAPIKey) SetId(v string) {
	o.Id = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *OrganizationReadWithAPIKey) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *OrganizationReadWithAPIKey) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *OrganizationReadWithAPIKey) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *OrganizationReadWithAPIKey) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *OrganizationReadWithAPIKey) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *OrganizationReadWithAPIKey) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetName returns the Name field value
func (o *OrganizationReadWithAPIKey) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *OrganizationReadWithAPIKey) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *OrganizationReadWithAPIKey) SetName(v string) {
	o.Name = v
}

// GetSettings returns the Settings field value if set, zero value otherwise.
func (o *OrganizationReadWithAPIKey) GetSettings() map[string]interface{} {
	if o == nil || IsNil(o.Settings) {
		var ret map[string]interface{}
		return ret
	}
	return o.Settings
}

// GetSettingsOk returns a tuple with the Settings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationReadWithAPIKey) GetSettingsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Settings) {
		return map[string]interface{}{}, false
	}
	return o.Settings, true
}

// HasSettings returns a boolean if a field has been set.
func (o *OrganizationReadWithAPIKey) HasSettings() bool {
	if o != nil && !IsNil(o.Settings) {
		return true
	}

	return false
}

// SetSettings gets a reference to the given map[string]interface{} and assigns it to the Settings field.
func (o *OrganizationReadWithAPIKey) SetSettings(v map[string]interface{}) {
	o.Settings = v
}

// GetApiKeyId returns the ApiKeyId field value if set, zero value otherwise.
func (o *OrganizationReadWithAPIKey) GetApiKeyId() string {
	if o == nil || IsNil(o.ApiKeyId) {
		var ret string
		return ret
	}
	return *o.ApiKeyId
}

// GetApiKeyIdOk returns a tuple with the ApiKeyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationReadWithAPIKey) GetApiKeyIdOk() (*string, bool) {
	if o == nil || IsNil(o.ApiKeyId) {
		return nil, false
	}
	return o.ApiKeyId, true
}

// HasApiKeyId returns a boolean if a field has been set.
func (o *OrganizationReadWithAPIKey) HasApiKeyId() bool {
	if o != nil && !IsNil(o.ApiKeyId) {
		return true
	}

	return false
}

// SetApiKeyId gets a reference to the given string and assigns it to the ApiKeyId field.
func (o *OrganizationReadWithAPIKey) SetApiKeyId(v string) {
	o.ApiKeyId = &v
}

// GetApiKeySecret returns the ApiKeySecret field value if set, zero value otherwise.
func (o *OrganizationReadWithAPIKey) GetApiKeySecret() string {
	if o == nil || IsNil(o.ApiKeySecret) {
		var ret string
		return ret
	}
	return *o.ApiKeySecret
}

// GetApiKeySecretOk returns a tuple with the ApiKeySecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationReadWithAPIKey) GetApiKeySecretOk() (*string, bool) {
	if o == nil || IsNil(o.ApiKeySecret) {
		return nil, false
	}
	return o.ApiKeySecret, true
}

// HasApiKeySecret returns a boolean if a field has been set.
func (o *OrganizationReadWithAPIKey) HasApiKeySecret() bool {
	if o != nil && !IsNil(o.ApiKeySecret) {
		return true
	}

	return false
}

// SetApiKeySecret gets a reference to the given string and assigns it to the ApiKeySecret field.
func (o *OrganizationReadWithAPIKey) SetApiKeySecret(v string) {
	o.ApiKeySecret = &v
}

func (o OrganizationReadWithAPIKey) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["key"] = o.Key
	}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["created_at"] = o.CreatedAt
	}
	if true {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Settings) {
		toSerialize["settings"] = o.Settings
	}
	if !IsNil(o.ApiKeyId) {
		toSerialize["api_key_id"] = o.ApiKeyId
	}
	if !IsNil(o.ApiKeySecret) {
		toSerialize["api_key_secret"] = o.ApiKeySecret
	}
	return json.Marshal(toSerialize)
}

type NullableOrganizationReadWithAPIKey struct {
	value *OrganizationReadWithAPIKey
	isSet bool
}

func (v NullableOrganizationReadWithAPIKey) Get() *OrganizationReadWithAPIKey {
	return v.value
}

func (v *NullableOrganizationReadWithAPIKey) Set(val *OrganizationReadWithAPIKey) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationReadWithAPIKey) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationReadWithAPIKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationReadWithAPIKey(val *OrganizationReadWithAPIKey) *NullableOrganizationReadWithAPIKey {
	return &NullableOrganizationReadWithAPIKey{value: val, isSet: true}
}

func (v NullableOrganizationReadWithAPIKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationReadWithAPIKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
