/*
Permit.io API

 Authorization as a service

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// checks if the TenantBlockRead type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TenantBlockRead{}

// TenantBlockRead struct for TenantBlockRead
type TenantBlockRead struct {
	// A unique id by which Permit will identify the tenant. The tenant key must be url-friendly (slugified).
	Key string `json:"key"`
	// A descriptive name for the tenant
	Name string `json:"name"`
	// an optional longer description of the tenant
	Description *string `json:"description,omitempty"`
	// Arbitraty tenant attributes that will be used to enforce attribute-based access control policies.
	Attributes map[string]interface{} `json:"attributes,omitempty"`
}

// NewTenantBlockRead instantiates a new TenantBlockRead object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenantBlockRead(key string, name string) *TenantBlockRead {
	this := TenantBlockRead{}
	this.Key = key
	this.Name = name
	return &this
}

// NewTenantBlockReadWithDefaults instantiates a new TenantBlockRead object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenantBlockReadWithDefaults() *TenantBlockRead {
	this := TenantBlockRead{}
	return &this
}

// GetKey returns the Key field value
func (o *TenantBlockRead) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *TenantBlockRead) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *TenantBlockRead) SetKey(v string) {
	o.Key = v
}

// GetName returns the Name field value
func (o *TenantBlockRead) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TenantBlockRead) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TenantBlockRead) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *TenantBlockRead) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantBlockRead) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *TenantBlockRead) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *TenantBlockRead) SetDescription(v string) {
	o.Description = &v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *TenantBlockRead) GetAttributes() map[string]interface{} {
	if o == nil || IsNil(o.Attributes) {
		var ret map[string]interface{}
		return ret
	}
	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantBlockRead) GetAttributesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Attributes) {
		return map[string]interface{}{}, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *TenantBlockRead) HasAttributes() bool {
	if o != nil && !IsNil(o.Attributes) {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given map[string]interface{} and assigns it to the Attributes field.
func (o *TenantBlockRead) SetAttributes(v map[string]interface{}) {
	o.Attributes = v
}

func (o TenantBlockRead) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TenantBlockRead) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Attributes) {
		toSerialize["attributes"] = o.Attributes
	}
	return toSerialize, nil
}

type NullableTenantBlockRead struct {
	value *TenantBlockRead
	isSet bool
}

func (v NullableTenantBlockRead) Get() *TenantBlockRead {
	return v.value
}

func (v *NullableTenantBlockRead) Set(val *TenantBlockRead) {
	v.value = val
	v.isSet = true
}

func (v NullableTenantBlockRead) IsSet() bool {
	return v.isSet
}

func (v *NullableTenantBlockRead) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenantBlockRead(val *TenantBlockRead) *NullableTenantBlockRead {
	return &NullableTenantBlockRead{value: val, isSet: true}
}

func (v NullableTenantBlockRead) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenantBlockRead) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
