/*
Permit.io API

 Authorization as a service

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// checks if the RelationshipTupleCreateBulkOperation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RelationshipTupleCreateBulkOperation{}

// RelationshipTupleCreateBulkOperation struct for RelationshipTupleCreateBulkOperation
type RelationshipTupleCreateBulkOperation struct {
	Operations []RelationshipTupleCreate `json:"operations"`
}

// NewRelationshipTupleCreateBulkOperation instantiates a new RelationshipTupleCreateBulkOperation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRelationshipTupleCreateBulkOperation(operations []RelationshipTupleCreate) *RelationshipTupleCreateBulkOperation {
	this := RelationshipTupleCreateBulkOperation{}
	this.Operations = operations
	return &this
}

// NewRelationshipTupleCreateBulkOperationWithDefaults instantiates a new RelationshipTupleCreateBulkOperation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRelationshipTupleCreateBulkOperationWithDefaults() *RelationshipTupleCreateBulkOperation {
	this := RelationshipTupleCreateBulkOperation{}
	return &this
}

// GetOperations returns the Operations field value
func (o *RelationshipTupleCreateBulkOperation) GetOperations() []RelationshipTupleCreate {
	if o == nil {
		var ret []RelationshipTupleCreate
		return ret
	}

	return o.Operations
}

// GetOperationsOk returns a tuple with the Operations field value
// and a boolean to check if the value has been set.
func (o *RelationshipTupleCreateBulkOperation) GetOperationsOk() ([]RelationshipTupleCreate, bool) {
	if o == nil {
		return nil, false
	}
	return o.Operations, true
}

// SetOperations sets field value
func (o *RelationshipTupleCreateBulkOperation) SetOperations(v []RelationshipTupleCreate) {
	o.Operations = v
}

func (o RelationshipTupleCreateBulkOperation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RelationshipTupleCreateBulkOperation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["operations"] = o.Operations
	return toSerialize, nil
}

type NullableRelationshipTupleCreateBulkOperation struct {
	value *RelationshipTupleCreateBulkOperation
	isSet bool
}

func (v NullableRelationshipTupleCreateBulkOperation) Get() *RelationshipTupleCreateBulkOperation {
	return v.value
}

func (v *NullableRelationshipTupleCreateBulkOperation) Set(val *RelationshipTupleCreateBulkOperation) {
	v.value = val
	v.isSet = true
}

func (v NullableRelationshipTupleCreateBulkOperation) IsSet() bool {
	return v.isSet
}

func (v *NullableRelationshipTupleCreateBulkOperation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRelationshipTupleCreateBulkOperation(val *RelationshipTupleCreateBulkOperation) *NullableRelationshipTupleCreateBulkOperation {
	return &NullableRelationshipTupleCreateBulkOperation{value: val, isSet: true}
}

func (v NullableRelationshipTupleCreateBulkOperation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRelationshipTupleCreateBulkOperation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
